"""The audio-transcript layer schema (where-graph-begins locked layer schema): `Source -> AudioSegment(coarse, owns the model-input WAV) -> Transcript(per-transcriber variants)` emitted by transcription, extended with the fine `Segment` spine by decomposition. Deterministic identity tuples per the stage-5 ratified rule; `Document` from the pre-CR-18 era dissolves into `Source`.

Docs: https://cj-mills.github.io/cjm-transcript-graph-schemaschema.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/schema.ipynb.

# %% auto #0
__all__ = ['TranscriptGraphLabels', 'source_node_id', 'audio_segment_node_id', 'transcript_node_id', 'segment_node_id',
           'SourceNode', 'AudioSegmentNode', 'TranscriptNode', 'TranscriptSliceRef', 'SegmentNode']

# %% ../nbs/schema.ipynb #76d0dd1c
from pathlib import Path
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from cjm_context_graph_layer.identity import derive_node_id
from cjm_context_graph_layer.grammar import OverlayRelations, attribution, make_edge
from cjm_context_graph_primitives.locators import FileRef, GraphNodeRef
from cjm_context_graph_primitives.slices import TimeSlice, CharSlice, FullContent
from cjm_context_graph_primitives.provenance import SourceRef

# %% ../nbs/schema.ipynb #ff94773a
class TranscriptGraphLabels:
    """Node labels of the audio-transcript layer schema."""
    SOURCE = "Source"               # Provenance root: one ingested media file
    AUDIO_SEGMENT = "AudioSegment"  # Coarse ~5-min spine member; owns the model-input WAV
    TRANSCRIPT = "Transcript"       # Per-transcriber text variant of one AudioSegment
    SEGMENT = "Segment"             # Fine spine member: one VAD chunk (immutable audio + correctable text)

    @classmethod
    def all(cls) -> list:  # All schema labels
        """All schema labels."""
        return [cls.SOURCE, cls.AUDIO_SEGMENT, cls.TRANSCRIPT, cls.SEGMENT]

# %% ../nbs/schema.ipynb #a5ea12db
def source_node_id(
    content_hash: str,  # Content hash of the source media file ("algo:hexdigest")
) -> str:  # Deterministic Source node id
    """Source identity = the ingested file's content hash (Thread-1 ingested-root identity)."""
    return derive_node_id("source", content_hash)

# %% ../nbs/schema.ipynb #794a019f
def audio_segment_node_id(
    source_id: str,  # Owning Source node id
    start: float,    # Boundary start (source-coordinate seconds)
    end: float,      # Boundary end (source-coordinate seconds)
) -> str:  # Deterministic AudioSegment node id
    """AudioSegment identity = (source, boundary range).

    Conversion-config-independent: the model-input WAV is payload/provenance,
    not identity — the boundary computation is pure and deterministic, so
    re-derivation reproduces the id."""
    return derive_node_id("audio-segment", source_id, start, end)

# %% ../nbs/schema.ipynb #6fe30fc8
def transcript_node_id(
    audio_segment_id: str,  # Owning AudioSegment node id
    transcriber: str,       # Transcriber capability name (e.g. "cjm-transcription-plugin-whisper")
    config_hash: str,       # Transcriber config hash
) -> str:  # Deterministic Transcript node id
    """Transcript identity = (audio segment, transcriber, config) — MIRRORS the
    capability cache key UNIQUE(audio_path, config_hash), so the graph node is
    the durable face of the cached row (the structural E13 fix)."""
    return derive_node_id("transcript", audio_segment_id, transcriber, config_hash)

# %% ../nbs/schema.ipynb #f0e4f510
def segment_node_id(
    audio_segment_id: str,  # Owning AudioSegment node id
    vad_config_hash: str,   # VAD capability config hash (skeleton identity input)
    chunk_start: float,     # VAD chunk start (chunk-local seconds within the AudioSegment)
    chunk_end: float,       # VAD chunk end (chunk-local seconds)
) -> str:  # Deterministic Segment node id
    """Fine Segment identity = audio-side only (audio segment, VAD config, chunk
    range) — so the skeleton's ids are SHARED across transcribers by
    construction (C4 "store agreement once" falls out of identity design)."""
    return derive_node_id("segment", audio_segment_id, vad_config_hash, chunk_start, chunk_end)

# %% ../nbs/schema.ipynb #d768584a
@dataclass
class SourceNode:
    """The provenance root: one ingested media file."""
    content_hash: str            # Content hash over the file ("algo:hexdigest"; the identity input)
    path: str                    # Original media path (location, may dangle; identity is the hash)
    title: Optional[str] = None  # Display title; None = path stem
    media_type: str = "audio"    # Media type

    @property
    def id(self) -> str:  # Deterministic node id
        """Deterministic node id."""
        return source_node_id(self.content_hash)

    def to_graph_node(self) -> Dict[str, Any]:  # Node wire dict
        """Build the Source node wire dict (root_kind=ingested; FileRef provenance)."""
        return {
            "id": self.id,
            "label": TranscriptGraphLabels.SOURCE,
            "properties": {
                "title": self.title or Path(self.path).stem,
                "media_type": self.media_type,
                "path": self.path,
                "root_kind": "ingested",
            },
            "sources": [SourceRef(locator=FileRef(path=self.path),
                                  content_hash=self.content_hash).to_dict()],
        }

# %% ../nbs/schema.ipynb #3d76c961
@dataclass
class AudioSegmentNode:
    """Coarse ~5-min spine member. Owns the model-input WAV (E14: the audio of
    record) as payload/provenance — the WAV is NOT its own node.

    Provenance note (deliberate): the SourceRef anchors the owned model-input
    WAV artifact (hash_file-verifiable). A hash over the sliced ORIGINAL source
    bytes is not materializable without extracting per-range artifacts (decoded
    ranges are not byte ranges); the structural chain to the Source rides the
    PART_OF edge + the start/end properties."""
    source: str                       # Owning Source node id
    index: int                        # Position in the coarse spine (0-based)
    start: float                      # Boundary start (source-coordinate seconds)
    end: float                        # Boundary end (source-coordinate seconds)
    model_input_path: str             # The 16kHz mono WAV consumed by transcription/VAD/FA
    model_input_hash: str             # Content hash over that WAV
    segment_path: Optional[str] = None  # Source-codec cut file (archival pointer)

    @property
    def id(self) -> str:  # Deterministic node id
        """Deterministic node id."""
        return audio_segment_node_id(self.source, self.start, self.end)

    def to_graph_node(self) -> Dict[str, Any]:  # Node wire dict
        """Build the AudioSegment node wire dict."""
        props: Dict[str, Any] = {
            "index": self.index,
            "start": self.start,
            "end": self.end,
            "model_input_path": self.model_input_path,
            "source_id": self.source,
        }
        if self.segment_path:
            props["segment_path"] = self.segment_path
        return {
            "id": self.id,
            "label": TranscriptGraphLabels.AUDIO_SEGMENT,
            "properties": props,
            "sources": [SourceRef(locator=FileRef(path=self.model_input_path),
                                  content_hash=self.model_input_hash).to_dict()],
        }

# %% ../nbs/schema.ipynb #9948f2c5
@dataclass
class TranscriptNode:
    """One transcriber's text for one AudioSegment (per-transcriber variants at
    the coarse layer — cross-transcriber divergence lives here, C4/C14)."""
    audio_segment: str            # Owning AudioSegment node id
    transcriber: str              # Transcriber capability name
    config_hash: str              # Transcriber config hash
    text: str                     # The transcript text (stored ONCE here; fine Segments slice into it)
    audio_hash: str               # Content hash of the consumed model-input WAV
    metadata: Dict[str, Any] = field(default_factory=dict)  # Transcriber-reported metadata
    asserted_at: Optional[float] = None  # Derivation timestamp; None = now

    @property
    def id(self) -> str:  # Deterministic node id
        """Deterministic node id."""
        return transcript_node_id(self.audio_segment, self.transcriber, self.config_hash)

    def to_graph_node(self) -> Dict[str, Any]:  # Node wire dict
        """Build the Transcript node wire dict (capability attribution included)."""
        props: Dict[str, Any] = {
            "transcriber": self.transcriber,
            "config_hash": self.config_hash,
            "text": self.text,
            "audio_segment_id": self.audio_segment,
        }
        if self.metadata:
            props["metadata"] = dict(self.metadata)
        props.update(attribution(f"capability:{self.transcriber}", method="transcribe",
                                 asserted_at=self.asserted_at))
        return {
            "id": self.id,
            "label": TranscriptGraphLabels.TRANSCRIPT,
            "properties": props,
            "sources": [SourceRef(locator=GraphNodeRef(node_id=self.audio_segment),
                                  content_hash=self.audio_hash,
                                  slice=FullContent("audio")).to_dict()],
        }

    def derived_edge(self) -> Dict[str, Any]:  # Edge wire dict
        """DERIVED_FROM edge: this Transcript derives from its AudioSegment."""
        return make_edge(self.id, self.audio_segment, OverlayRelations.DERIVED_FROM)

# %% ../nbs/schema.ipynb #0c830160
@dataclass
class TranscriptSliceRef:
    """One per-transcriber char-range reference for a fine Segment: where this
    segment's text lives inside a Transcript node's text (Thread-1
    slices-until-promoted — variants are slices, never duplicated fine text)."""
    transcript: str  # Transcript node id
    start_char: int  # Slice start into the Transcript's text
    end_char: int    # Slice end
    text: str        # The sliced text (content-hashed for the ref)

    def to_source_ref(self) -> Dict[str, Any]:  # SourceRef wire dict
        """Build the slice-shaped provenance ref."""
        return SourceRef(locator=GraphNodeRef(node_id=self.transcript),
                         content_hash=SourceRef.compute_hash(self.text.encode()),
                         slice=CharSlice(start=self.start_char, end=self.end_char)).to_dict()

# %% ../nbs/schema.ipynb #fecb183e
@dataclass
class SegmentNode:
    """Fine spine member: one VAD chunk — IMMUTABLE audio range + CORRECTABLE
    text (the immutable-audio/mutable-text spine seam).

    Layer-0 `text` is the ACCURACY transcriber's alignment; the designation is
    per-segment provenance, not global config (`text_from` names the
    authoritative Transcript; every transcriber's char range rides
    `text_slices`, the authoritative one included)."""
    audio_segment: str        # Owning AudioSegment node id
    vad_config_hash: str      # VAD config hash (skeleton identity input)
    chunk_start: float        # VAD chunk start (chunk-local seconds within the AudioSegment WAV)
    chunk_end: float          # VAD chunk end (chunk-local seconds)
    index: int                # Source-wide fine-spine index (0-based)
    start_time: float         # Source-coordinate start (navigation)
    end_time: float           # Source-coordinate end
    text: str = ""            # Layer-0 text (accuracy alignment; "" = no aligned words, D14 class)
    audio_hash: str = ""      # Content hash of the owning AudioSegment's model-input WAV
    source: Optional[str] = None     # Source node id (convenience for direct filters)
    text_from: Optional[str] = None  # Authoritative Transcript node id (None when text is empty)
    text_slices: List[TranscriptSliceRef] = field(default_factory=list)  # All per-transcriber slice refs

    @property
    def id(self) -> str:  # Deterministic node id
        """Deterministic node id (audio-side identity; shared across transcribers)."""
        return segment_node_id(self.audio_segment, self.vad_config_hash,
                               self.chunk_start, self.chunk_end)

    def to_graph_node(self) -> Dict[str, Any]:  # Node wire dict
        """Build the Segment node wire dict (audio ref + per-transcriber text slice refs)."""
        props: Dict[str, Any] = {
            "text": self.text,
            "index": self.index,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "chunk_start": self.chunk_start,
            "chunk_end": self.chunk_end,
            "audio_segment_id": self.audio_segment,
        }
        if self.source:
            props["source_id"] = self.source
        if self.text_from:
            props["text_from"] = self.text_from
        sources = [SourceRef(locator=GraphNodeRef(node_id=self.audio_segment),
                             content_hash=self.audio_hash,
                             slice=TimeSlice(start=self.chunk_start, end=self.chunk_end)).to_dict()]
        sources.extend(ts.to_source_ref() for ts in self.text_slices)
        return {
            "id": self.id,
            "label": TranscriptGraphLabels.SEGMENT,
            "properties": props,
            "sources": sources,
        }
